---
include:
  - board: seeeduino_xiao_ble
    shield: corne_xiao_v2_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: corne_xiao_v2_right rgbled_adapter

  - board: seeeduino_xiao_ble
    shield: settings_reset
